// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function AddAccount(arg1:auth.LaunchAccount):Promise<void>;

export function AuthlibLogin(arg1:string,arg2:string,arg3:string):Promise<Array<bindings.AuthlibProfileView>>;

export function CancelMicrosoftLogin():Promise<void>;

export function ConfirmAuthlibProfile(arg1:number):Promise<string>;

export function CreateOfflineAccount(arg1:string):Promise<auth.LaunchAccount>;

export function DismissMicrosoftLoginState():Promise<void>;

export function GetAccountStableKey(arg1:auth.LaunchAccount):Promise<string>;

export function GetAccountSummaries():Promise<Array<bindings.AccountSummary>>;

export function GetAccounts():Promise<Array<auth.LaunchAccount>>;

export function GetAvatarUrl(arg1:string):Promise<string>;

export function GetMicrosoftLoginState():Promise<bindings.MicrosoftBrowserLoginState>;

export function GetMinecraftProfile(arg1:string):Promise<bindings.MinecraftProfile>;

export function GetOfflineSkinCatalog():Promise<Array<bindings.OfflineSkinChoice>>;

export function GetSelectedAccount():Promise<auth.LaunchAccount>;

export function GetSkinTexture(arg1:string):Promise<bindings.SkinTexture>;

export function HasOfflineName(arg1:string):Promise<boolean>;

export function LoginMicrosoft():Promise<string>;

export function LoginMicrosoftBrowser(arg1:string):Promise<void>;

export function MoveAccountToTop(arg1:auth.LaunchAccount):Promise<void>;

export function RefreshSkinTexture(arg1:string):Promise<bindings.SkinTexture>;

export function RemoveAccount(arg1:auth.LaunchAccount):Promise<void>;

export function ResolveAuthlibServer(arg1:string):Promise<auth.AuthlibServerInfo>;

export function SelectAccountByStableKey(arg1:string):Promise<boolean>;

export function SetActiveCape(arg1:string,arg2:string):Promise<void>;

export function SetOfflineSkin(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateAuthlibAccount(arg1:auth.LaunchAccount,arg2:auth.AuthlibCredential):Promise<void>;

export function UpdateMicrosoftAccount(arg1:auth.LaunchAccount,arg2:auth.MicrosoftAccount):Promise<void>;

export function UpdateOfflineSkin(arg1:auth.LaunchAccount,arg2:string):Promise<void>;

export function UploadSkin(arg1:string,arg2:string,arg3:string):Promise<void>;
