// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['bindings']['AccountAPI']['AddAccount'](arg1);
}

export function AuthlibLogin(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['AccountAPI']['AuthlibLogin'](arg1, arg2, arg3, arg4);
}

export function CancelMicrosoftLogin() {
  return window['go']['bindings']['AccountAPI']['CancelMicrosoftLogin']();
}

export function CreateOfflineAccount(arg1) {
  return window['go']['bindings']['AccountAPI']['CreateOfflineAccount'](arg1);
}

export function DismissMicrosoftLoginState() {
  return window['go']['bindings']['AccountAPI']['DismissMicrosoftLoginState']();
}

export function GetAccountStableKey(arg1) {
  return window['go']['bindings']['AccountAPI']['GetAccountStableKey'](arg1);
}

export function GetAccountSummaries() {
  return window['go']['bindings']['AccountAPI']['GetAccountSummaries']();
}

export function ConfirmAuthlibProfile(arg1) {
  return window['go']['bindings']['AccountAPI']['ConfirmAuthlibProfile'](arg1);
}

export function GetAccounts() {
  return window['go']['bindings']['AccountAPI']['GetAccounts']();
}

export function GetAuthlibClientToken() {
  return window['go']['bindings']['AccountAPI']['GetAuthlibClientToken']();
}

export function GetAvatarUrl(arg1) {
  return window['go']['bindings']['AccountAPI']['GetAvatarUrl'](arg1);
}

export function GetMicrosoftLoginState() {
  return window['go']['bindings']['AccountAPI']['GetMicrosoftLoginState']();
}

export function GetMinecraftProfile(arg1) {
  return window['go']['bindings']['AccountAPI']['GetMinecraftProfile'](arg1);
}

export function GetOfflineSkinCatalog() {
  return window['go']['bindings']['AccountAPI']['GetOfflineSkinCatalog']();
}

export function GetSelectedAccount() {
  return window['go']['bindings']['AccountAPI']['GetSelectedAccount']();
}

export function GetSkinTexture(arg1) {
  return window['go']['bindings']['AccountAPI']['GetSkinTexture'](arg1);
}

export function HasOfflineName(arg1) {
  return window['go']['bindings']['AccountAPI']['HasOfflineName'](arg1);
}

export function LoginMicrosoft() {
  return window['go']['bindings']['AccountAPI']['LoginMicrosoft']();
}

export function LoginMicrosoftBrowser(arg1) {
  return window['go']['bindings']['AccountAPI']['LoginMicrosoftBrowser'](arg1);
}

export function MoveAccountToTop(arg1) {
  return window['go']['bindings']['AccountAPI']['MoveAccountToTop'](arg1);
}

export function RefreshSkinTexture(arg1) {
  return window['go']['bindings']['AccountAPI']['RefreshSkinTexture'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['bindings']['AccountAPI']['RemoveAccount'](arg1);
}

export function ResolveAuthlibServer(arg1) {
  return window['go']['bindings']['AccountAPI']['ResolveAuthlibServer'](arg1);
}

export function SelectAccountByStableKey(arg1) {
  return window['go']['bindings']['AccountAPI']['SelectAccountByStableKey'](arg1);
}

export function SetActiveCape(arg1, arg2) {
  return window['go']['bindings']['AccountAPI']['SetActiveCape'](arg1, arg2);
}

export function SetOfflineSkin(arg1, arg2) {
  return window['go']['bindings']['AccountAPI']['SetOfflineSkin'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['bindings']['AccountAPI']['Startup'](arg1);
}

export function UpdateAuthlibAccount(arg1, arg2) {
  return window['go']['bindings']['AccountAPI']['UpdateAuthlibAccount'](arg1, arg2);
}

export function UpdateMicrosoftAccount(arg1, arg2) {
  return window['go']['bindings']['AccountAPI']['UpdateMicrosoftAccount'](arg1, arg2);
}

export function UpdateOfflineSkin(arg1, arg2) {
  return window['go']['bindings']['AccountAPI']['UpdateOfflineSkin'](arg1, arg2);
}

export function UploadSkin(arg1, arg2, arg3) {
  return window['go']['bindings']['AccountAPI']['UploadSkin'](arg1, arg2, arg3);
}
