// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddJava(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['AddJava'](arg1, arg2);
}

export function AddProfileFolder(arg1) {
  return window['go']['bindings']['ConfigAPI']['AddProfileFolder'](arg1);
}

export function AutoDetectJava() {
  return window['go']['bindings']['ConfigAPI']['AutoDetectJava']();
}

export function ClearGameDirectory() {
  return window['go']['bindings']['ConfigAPI']['ClearGameDirectory']();
}

export function ClearValue(arg1) {
  return window['go']['bindings']['ConfigAPI']['ClearValue'](arg1);
}

export function GetDefaultVersionIsolation() {
  return window['go']['bindings']['ConfigAPI']['GetDefaultVersionIsolation']();
}

export function GetGameDirectory() {
  return window['go']['bindings']['ConfigAPI']['GetGameDirectory']();
}

export function GetJavaExecutable() {
  return window['go']['bindings']['ConfigAPI']['GetJavaExecutable']();
}

export function GetJavaPaths() {
  return window['go']['bindings']['ConfigAPI']['GetJavaPaths']();
}

export function GetJavaVersion() {
  return window['go']['bindings']['ConfigAPI']['GetJavaVersion']();
}

export function GetProfileFolders() {
  return window['go']['bindings']['ConfigAPI']['GetProfileFolders']();
}

export function GetProxySettings() {
  return window['go']['bindings']['ConfigAPI']['GetProxySettings']();
}

export function GetStorageDirectory() {
  return window['go']['bindings']['ConfigAPI']['GetStorageDirectory']();
}

export function GetValue(arg1) {
  return window['go']['bindings']['ConfigAPI']['GetValue'](arg1);
}

export function GetVerifyFilesBeforeLaunch() {
  return window['go']['bindings']['ConfigAPI']['GetVerifyFilesBeforeLaunch']();
}

export function GetVersionProfile(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['GetVersionProfile'](arg1, arg2);
}

export function IsPortableMode() {
  return window['go']['bindings']['ConfigAPI']['IsPortableMode']();
}

export function LoadGlobalLaunchSettings() {
  return window['go']['bindings']['ConfigAPI']['LoadGlobalLaunchSettings']();
}

export function RemoveJava(arg1) {
  return window['go']['bindings']['ConfigAPI']['RemoveJava'](arg1);
}

export function RemoveProfileFolder(arg1) {
  return window['go']['bindings']['ConfigAPI']['RemoveProfileFolder'](arg1);
}

export function SaveDefaultVersionIsolation(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveDefaultVersionIsolation'](arg1);
}

export function SaveGameDirectory(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveGameDirectory'](arg1);
}

export function SaveGlobalLaunchSettings(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveGlobalLaunchSettings'](arg1);
}

export function SaveJava(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['SaveJava'](arg1, arg2);
}

export function SaveProxySettings(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveProxySettings'](arg1);
}

export function SaveVerifyFilesBeforeLaunch(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveVerifyFilesBeforeLaunch'](arg1);
}

export function SaveVersionProfile(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveVersionProfile'](arg1);
}

export function SetPrimaryJava(arg1) {
  return window['go']['bindings']['ConfigAPI']['SetPrimaryJava'](arg1);
}

export function SetValue(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['SetValue'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['bindings']['ConfigAPI']['Startup'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['bindings']['ConfigAPI']['TestProxy'](arg1);
}
