// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {config} from '../models';
import {network} from '../models';
import {context} from '../models';

export function AddJava(arg1:string,arg2:string):Promise<boolean>;

export function AddProfileFolder(arg1:string):Promise<boolean>;

export function AutoDetectJava():Promise<bindings.JavaScanResult>;

export function ClearGameDirectory():Promise<void>;

export function ClearValue(arg1:string):Promise<boolean>;

export function GetDefaultVersionIsolation():Promise<boolean>;

export function GetGameDirectory():Promise<string>;

export function GetJavaExecutable():Promise<string>;

export function GetJavaPaths():Promise<Array<config.JavaPathItem>>;

export function GetJavaVersion():Promise<string>;

export function GetProfileFolders():Promise<Array<string>>;

export function GetProxySettings():Promise<network.ProxySettings>;

export function GetStorageDirectory():Promise<string>;

export function GetValue(arg1:string):Promise<string>;

export function GetVerifyFilesBeforeLaunch():Promise<boolean>;

export function GetVersionProfile(arg1:string,arg2:string):Promise<config.GameVersionProfile>;

export function IsPortableMode():Promise<boolean>;

export function LoadGlobalLaunchSettings():Promise<config.GlobalLaunchSettings>;

export function RemoveJava(arg1:string):Promise<boolean>;

export function RemoveProfileFolder(arg1:string):Promise<boolean>;

export function SaveDefaultVersionIsolation(arg1:any):Promise<void>;

export function SaveGameDirectory(arg1:string):Promise<boolean>;

export function SaveGlobalLaunchSettings(arg1:config.GlobalLaunchSettings):Promise<boolean>;

export function SaveJava(arg1:string,arg2:string):Promise<boolean>;

export function SaveProxySettings(arg1:network.ProxySettings):Promise<void>;

export function SaveVerifyFilesBeforeLaunch(arg1:boolean):Promise<void>;

export function SaveVersionProfile(arg1:config.GameVersionProfile):Promise<boolean>;

export function SetPrimaryJava(arg1:string):Promise<boolean>;

export function SetValue(arg1:string,arg2:string):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestProxy(arg1:network.ProxySettings):Promise<string>;
