// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';
import {content} from '../models';
import {context} from '../models';

export function ApplyContentUpdate(arg1:string,arg2:string,arg3:string):Promise<download.ContentUpdateApplyResult>;

export function CheckInstanceContentUpdates(arg1:string,arg2:string,arg3:string):Promise<download.ContentUpdateCheckResult>;

export function CreateInstanceSnapshot(arg1:string,arg2:string,arg3:string):Promise<content.SaveSnapshot>;

export function CreateSaveSnapshot(arg1:string,arg2:string,arg3:string):Promise<content.SaveSnapshot>;

export function DeleteInstanceSnapshot(arg1:string,arg2:string):Promise<void>;

export function DeleteSave(arg1:string):Promise<void>;

export function DeleteSaveSnapshot(arg1:string,arg2:string):Promise<void>;

export function DownloadContentUpdate(arg1:string,arg2:string,arg3:string):Promise<download.ContentUpdateApplyResult>;

export function ExportSave(arg1:string,arg2:string):Promise<string>;

export function GetContentVersionOptions(arg1:string,arg2:string,arg3:string,arg4:string):Promise<download.ContentVersionOptions>;

export function GetInstanceVisual(arg1:string,arg2:string):Promise<content.GameInstanceVisual>;

export function ImportSave(arg1:string,arg2:string):Promise<string>;

export function ListInstanceSnapshots(arg1:string):Promise<Array<content.SaveSnapshot>>;

export function ListSaveSnapshots(arg1:string):Promise<Array<content.SaveSnapshot>>;

export function ReadMods(arg1:string):Promise<Array<content.GameContentEntry>>;

export function ReadResourcePacks(arg1:string):Promise<Array<content.GameContentEntry>>;

export function ReadSaves(arg1:string):Promise<Array<content.GameContentEntry>>;

export function ReadShaders(arg1:string):Promise<Array<content.GameContentEntry>>;

export function RemoveCustomIcon(arg1:string,arg2:string):Promise<boolean>;

export function RollbackInstanceSnapshot(arg1:string,arg2:string):Promise<content.SaveSnapshot>;

export function RollbackSaveSnapshot(arg1:string,arg2:string):Promise<content.SaveSnapshot>;

export function SetCustomIcon(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetInstanceSnapshotColor(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSaveSnapshotColor(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleContentEntry(arg1:string,arg2:boolean):Promise<void>;
