// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyContentUpdate(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['ApplyContentUpdate'](arg1, arg2, arg3);
}

export function CheckInstanceContentUpdates(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['CheckInstanceContentUpdates'](arg1, arg2, arg3);
}

export function CopyFileIntoDirectory(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['CopyFileIntoDirectory'](arg1, arg2);
}

export function CreateInstanceSnapshot(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['CreateInstanceSnapshot'](arg1, arg2, arg3);
}

export function CreateSaveSnapshot(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['CreateSaveSnapshot'](arg1, arg2, arg3);
}

export function DeleteInstanceSnapshot(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['DeleteInstanceSnapshot'](arg1, arg2);
}

export function DeleteSave(arg1) {
  return window['go']['bindings']['ContentAPI']['DeleteSave'](arg1);
}

export function DeleteSaveSnapshot(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['DeleteSaveSnapshot'](arg1, arg2);
}

export function DownloadContentUpdate(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['DownloadContentUpdate'](arg1, arg2, arg3);
}

export function ExportSave(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['ExportSave'](arg1, arg2);
}

export function GetContentVersionOptions(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['ContentAPI']['GetContentVersionOptions'](arg1, arg2, arg3, arg4);
}

export function GetInstanceVisual(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['GetInstanceVisual'](arg1, arg2);
}

export function ImportSave(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['ImportSave'](arg1, arg2);
}

export function ListInstanceSnapshots(arg1) {
  return window['go']['bindings']['ContentAPI']['ListInstanceSnapshots'](arg1);
}

export function ListSaveSnapshots(arg1) {
  return window['go']['bindings']['ContentAPI']['ListSaveSnapshots'](arg1);
}

export function LookupModNameTranslations(arg1) {
  return window['go']['bindings']['ContentAPI']['LookupModNameTranslations'](arg1);
}

export function ReadMods(arg1) {
  return window['go']['bindings']['ContentAPI']['ReadMods'](arg1);
}

export function ReadResourcePacks(arg1) {
  return window['go']['bindings']['ContentAPI']['ReadResourcePacks'](arg1);
}

export function ReadSaves(arg1) {
  return window['go']['bindings']['ContentAPI']['ReadSaves'](arg1);
}

export function ReadShaders(arg1) {
  return window['go']['bindings']['ContentAPI']['ReadShaders'](arg1);
}

export function RefreshModNameTranslations(arg1) {
  return window['go']['bindings']['ContentAPI']['RefreshModNameTranslations'](arg1);
}

export function RemoveCustomIcon(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['RemoveCustomIcon'](arg1, arg2);
}

export function RewindSummary() {
  return window['go']['bindings']['ContentAPI']['RewindSummary']();
}

export function RollbackInstanceSnapshot(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['RollbackInstanceSnapshot'](arg1, arg2);
}

export function RollbackSaveSnapshot(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['RollbackSaveSnapshot'](arg1, arg2);
}

export function SetCustomIcon(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['SetCustomIcon'](arg1, arg2, arg3);
}

export function SetInstanceSnapshotColor(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['SetInstanceSnapshotColor'](arg1, arg2, arg3);
}

export function SetSaveSnapshotColor(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['SetSaveSnapshotColor'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['bindings']['ContentAPI']['Startup'](arg1);
}

export function ToggleContentEntry(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['ToggleContentEntry'](arg1, arg2);
}
