// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {download} from '../models';
import {context} from '../models';

export function ApplyVersionFilter(arg1:Array<models.MinecraftVersion>,arg2:string):Promise<Array<models.MinecraftVersion>>;

export function CancelContentTask(arg1:string):Promise<boolean>;

export function CancelDownload():Promise<boolean>;

export function CreateDefaultInstanceName(arg1:download.ModLoaderType,arg2:string,arg3:string):Promise<string>;

export function DeleteJavaRuntime(arg1:string):Promise<void>;

export function DownloadFileToInstance(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function DownloadFileToPath(arg1:string,arg2:string):Promise<void>;

export function DownloadResourceVersion(arg1:models.ResourceDownloadRequest):Promise<models.ResourceDownloadResult>;

export function GetActiveDownloadSourceName():Promise<string>;

export function GetAllDownloadSources():Promise<Array<download.DownloadSource>>;

export function GetContentTasks():Promise<Array<download.ContentTaskSnapshot>>;

export function GetCurrentDownloadSnapshot():Promise<download.GameDownloadSnapshot>;

export function GetFallbackDownloadSourceName():Promise<string>;

export function GetInstalledJavaRuntimes():Promise<Array<download.InstalledJavaRuntime>>;

export function GetModLoaderVersions(arg1:download.ModLoaderType,arg2:string):Promise<Array<download.ModLoaderVersion>>;

export function GetParallelDownloads():Promise<number>;

export function GetResourceSources():Promise<Array<models.ResourceSourceInfo>>;

export function GetSourceLatencies():Promise<Array<download.SourceLatency>>;

export function GetSpeedLimitKbps():Promise<number>;

export function GetVersions():Promise<Array<models.MinecraftVersion>>;

export function InstallJavaRuntime(arg1:download.JavaDownloadCandidate):Promise<download.InstalledJavaRuntime>;

export function InstallModpackToInstance(arg1:string,arg2:string):Promise<download.ModpackInstallResult>;

export function IsDownloadPaused():Promise<boolean>;

export function ListResourceVersions(arg1:models.ResourceVersionRequest):Promise<models.ResourceVersionList>;

export function PauseDownload():Promise<boolean>;

export function QueryAvailableJavaVersions(arg1:download.JavaVendor):Promise<Array<download.JavaDownloadCandidate>>;

export function ReadModpackRequirements(arg1:string):Promise<download.ModpackRequirements>;

export function ResolveContentDirectoryForInstance(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ResumeDownload():Promise<boolean>;

export function SaveActiveDownloadSource(arg1:download.DownloadSource):Promise<void>;

export function SaveCurseForgeAPIKey(arg1:string):Promise<boolean>;

export function SaveFallbackDownloadSource(arg1:download.DownloadSource):Promise<void>;

export function SaveParallelDownloads(arg1:number):Promise<void>;

export function SaveSpeedLimitKbps(arg1:number):Promise<void>;

export function SearchResources(arg1:models.ResourceSearchRequest):Promise<models.ResourceSearchResult>;

export function StartDownload(arg1:models.MinecraftVersion):Promise<boolean>;

export function StartModLoaderDownload(arg1:models.MinecraftVersion,arg2:download.ModLoaderVersion,arg3:string,arg4:boolean):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
