// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyInstance(arg1, arg2) {
  return window['go']['bindings']['InstanceAPI']['CopyInstance'](arg1, arg2);
}

export function DeleteInstance(arg1, arg2) {
  return window['go']['bindings']['InstanceAPI']['DeleteInstance'](arg1, arg2);
}

export function EnsureDefaultMinecraftDirectory() {
  return window['go']['bindings']['InstanceAPI']['EnsureDefaultMinecraftDirectory']();
}

export function GetCurrentInstanceSnapshot() {
  return window['go']['bindings']['InstanceAPI']['GetCurrentInstanceSnapshot']();
}

export function GetDefaultMinecraftDirectory() {
  return window['go']['bindings']['InstanceAPI']['GetDefaultMinecraftDirectory']();
}

export function GetInstalledVersionIds(arg1) {
  return window['go']['bindings']['InstanceAPI']['GetInstalledVersionIds'](arg1);
}

export function GetInstanceDisplayVersion(arg1) {
  return window['go']['bindings']['InstanceAPI']['GetInstanceDisplayVersion'](arg1);
}

export function GetVersionDetails(arg1) {
  return window['go']['bindings']['InstanceAPI']['GetVersionDetails'](arg1);
}

export function RefreshInstances(arg1) {
  return window['go']['bindings']['InstanceAPI']['RefreshInstances'](arg1);
}

export function RenameInstance(arg1, arg2) {
  return window['go']['bindings']['InstanceAPI']['RenameInstance'](arg1, arg2);
}

export function ResolveInstanceIsolation(arg1, arg2) {
  return window['go']['bindings']['InstanceAPI']['ResolveInstanceIsolation'](arg1, arg2);
}

export function ScanImportableInstances() {
  return window['go']['bindings']['InstanceAPI']['ScanImportableInstances']();
}

export function SelectInstance(arg1) {
  return window['go']['bindings']['InstanceAPI']['SelectInstance'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['InstanceAPI']['Startup'](arg1);
}

export function TryResolveExternalInstance(arg1) {
  return window['go']['bindings']['InstanceAPI']['TryResolveExternalInstance'](arg1);
}
