// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {instance} from '../models';
import {config} from '../models';
import {context} from '../models';

export function CopyInstance(arg1:string,arg2:string):Promise<string>;

export function DeleteInstance(arg1:string,arg2:string):Promise<void>;

export function DeleteInstanceJavaConfig(arg1:string):Promise<void>;

export function EnsureDefaultMinecraftDirectory():Promise<string>;

export function GetCurrentInstanceSnapshot():Promise<instance.GameInstanceSnapshot>;

export function GetDefaultMinecraftDirectory():Promise<string>;

export function GetInstalledVersionIds(arg1:string):Promise<Array<string>>;

export function GetInstanceDisplayVersion(arg1:string):Promise<string>;

export function GetInstanceJavaConfig(arg1:string):Promise<config.JavaConfig>;

export function GetVersionDetails(arg1:string):Promise<instance.GameVersionDetails>;

export function RefreshInstances(arg1:string):Promise<instance.GameInstanceSnapshot>;

export function RenameInstance(arg1:string,arg2:string):Promise<string>;

export function ResolveInstanceIsolation(arg1:instance.GameInstanceSnapshot,arg2:string):Promise<instance.GameVersionLayout>;

export function SaveInstanceJavaConfig(arg1:string,arg2:config.JavaConfig):Promise<void>;

export function ScanImportableInstances():Promise<Array<instance.ImportableInstance>>;

export function SelectInstance(arg1:string):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;

export function TryResolveExternalInstance(arg1:string):Promise<instance.ExternalGameInstanceLayout|boolean>;
