// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launch} from '../models';
import {config} from '../models';
import {context} from '../models';

export function DeleteDirectory(arg1:string):Promise<void>;

export function DetectJavaMajorVersion(arg1:string):Promise<any>;

export function DiagnoseCrash():Promise<launch.CrashDiagnosis>;

export function GetLaunchProvenance():Promise<launch.LaunchProvenanceReport>;

export function GetLaunchProvenanceVersionId():Promise<string>;

export function GetLaunchSnapshot():Promise<launch.GameLaunchSnapshot>;

export function GetLogText():Promise<string>;

export function GetManualMaximumMemoryMb():Promise<number>;

export function GetMemorySliderMaximum():Promise<number>;

export function GetPlaytimeStats():Promise<Array<config.PlaytimeRecord>>;

export function GetSystemMemory():Promise<launch.SystemMemorySnapshot>;

export function IsAutomaticMemoryAdjustmentEnabled():Promise<boolean>;

export function Launch(arg1:string,arg2:any,arg3:string):Promise<launch.LaunchResult>;

export function LaunchVersion(arg1:string,arg2:string,arg3:any,arg4:string):Promise<launch.LaunchResult>;

export function SaveManualMaximumMemoryMb(arg1:number):Promise<boolean>;

export function SetAutomaticMemoryAdjustmentEnabled(arg1:boolean):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopGame():Promise<launch.LaunchResult>;
