// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modpack} from '../models';
import {solo} from '../models';
import {context} from '../models';

export function CollectExportContent(arg1:string):Promise<Array<modpack.ModpackContentItem>>;

export function DownloadSoloStub():Promise<solo.StubStatus>;

export function ExportModpack(arg1:modpack.ModpackExportOptions,arg2:string,arg3:string):Promise<modpack.ModpackExportResult>;

export function ExportSoloPack(arg1:solo.SoloExportOptions,arg2:string):Promise<modpack.ModpackExportResult>;

export function GetSoloStubStatus():Promise<solo.StubStatus>;

export function LoadExportProfile(arg1:string):Promise<modpack.ModpackExportProfile>;

export function NewExportOptions():Promise<modpack.ModpackExportOptions>;

export function SaveExportProfile(arg1:string,arg2:modpack.ModpackExportProfile):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
