// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {online} from '../models';
import {context} from '../models';

export function GenerateAPIKey():Promise<string>;

export function GetRelayList():Promise<string>;

export function GetRuntime(arg1:string):Promise<online.Runtime>;

export function GetSettings():Promise<online.Settings>;

export function Host(arg1:online.HostOptions):Promise<void>;

export function InstallTerracotta():Promise<online.TerracottaInstallResult>;

export function Join(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Leave(arg1:string):Promise<void>;

export function ListLocalServers():Promise<Array<online.LocalServer>>;

export function ListProviders():Promise<Array<online.ProviderInfo>>;

export function ListRelayOptions():Promise<Array<online.RelayOption>>;

export function ListStatuses():Promise<Array<online.Status>>;

export function OpenPage(arg1:string):Promise<void>;

export function ProbeRelays():Promise<Array<online.RelayProbe>>;

export function SaveRelayList(arg1:string):Promise<void>;

export function SaveSettings(arg1:online.Settings):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function ShutdownProvider(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UseFastestRelay():Promise<online.RelayProbe>;
