// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateAPIKey() {
  return window['go']['bindings']['OnlineAPI']['GenerateAPIKey']();
}

export function GetRelayList() {
  return window['go']['bindings']['OnlineAPI']['GetRelayList']();
}

export function GetRuntime(arg1) {
  return window['go']['bindings']['OnlineAPI']['GetRuntime'](arg1);
}

export function GetSettings() {
  return window['go']['bindings']['OnlineAPI']['GetSettings']();
}

export function Host(arg1) {
  return window['go']['bindings']['OnlineAPI']['Host'](arg1);
}

export function InstallTerracotta() {
  return window['go']['bindings']['OnlineAPI']['InstallTerracotta']();
}

export function Join(arg1, arg2, arg3) {
  return window['go']['bindings']['OnlineAPI']['Join'](arg1, arg2, arg3);
}

export function Leave(arg1) {
  return window['go']['bindings']['OnlineAPI']['Leave'](arg1);
}

export function ListLocalServers() {
  return window['go']['bindings']['OnlineAPI']['ListLocalServers']();
}

export function ListProviders() {
  return window['go']['bindings']['OnlineAPI']['ListProviders']();
}

export function ListRelayOptions() {
  return window['go']['bindings']['OnlineAPI']['ListRelayOptions']();
}

export function ListStatuses() {
  return window['go']['bindings']['OnlineAPI']['ListStatuses']();
}

export function OpenPage(arg1) {
  return window['go']['bindings']['OnlineAPI']['OpenPage'](arg1);
}

export function ProbeRelays() {
  return window['go']['bindings']['OnlineAPI']['ProbeRelays']();
}

export function SaveRelayList(arg1) {
  return window['go']['bindings']['OnlineAPI']['SaveRelayList'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['bindings']['OnlineAPI']['SaveSettings'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['bindings']['OnlineAPI']['Shutdown'](arg1);
}

export function ShutdownProvider(arg1) {
  return window['go']['bindings']['OnlineAPI']['ShutdownProvider'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['OnlineAPI']['Startup'](arg1);
}

export function UseFastestRelay() {
  return window['go']['bindings']['OnlineAPI']['UseFastestRelay']();
}
