// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';

export function CreatePluginScaffold(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EnsurePluginsDirectory():Promise<string>;

export function InstallPluginArchive(arg1:string):Promise<string>;

export function InstallPluginDirectory(arg1:string):Promise<string>;

export function ListPlugins():Promise<Array<bindings.PluginInfo>>;

export function OpenPluginPath(arg1:string,arg2:string):Promise<void>;

export function PackagePlugin(arg1:string,arg2:string):Promise<string>;

export function SavePluginManifest(arg1:string,arg2:string):Promise<void>;

export function SetPluginDisabled(arg1:string,arg2:boolean):Promise<void>;

export function UninstallPlugin(arg1:string):Promise<void>;
