// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePluginScaffold(arg1, arg2, arg3) {
  return window['go']['bindings']['PluginAPI']['CreatePluginScaffold'](arg1, arg2, arg3);
}

export function EnsurePluginsDirectory() {
  return window['go']['bindings']['PluginAPI']['EnsurePluginsDirectory']();
}

export function InstallPluginArchive(arg1) {
  return window['go']['bindings']['PluginAPI']['InstallPluginArchive'](arg1);
}

export function InstallPluginDirectory(arg1) {
  return window['go']['bindings']['PluginAPI']['InstallPluginDirectory'](arg1);
}

export function ListPlugins() {
  return window['go']['bindings']['PluginAPI']['ListPlugins']();
}

export function OpenPluginPath(arg1, arg2) {
  return window['go']['bindings']['PluginAPI']['OpenPluginPath'](arg1, arg2);
}

export function PackagePlugin(arg1, arg2) {
  return window['go']['bindings']['PluginAPI']['PackagePlugin'](arg1, arg2);
}

export function SavePluginManifest(arg1, arg2) {
  return window['go']['bindings']['PluginAPI']['SavePluginManifest'](arg1, arg2);
}

export function SetPluginDisabled(arg1, arg2) {
  return window['go']['bindings']['PluginAPI']['SetPluginDisabled'](arg1, arg2);
}

export function UninstallPlugin(arg1) {
  return window['go']['bindings']['PluginAPI']['UninstallPlugin'](arg1);
}
