// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcserver} from '../models';
import {models} from '../models';
import {context} from '../models';

export function CreateServer(arg1:mcserver.CreateOptions):Promise<string>;

export function CreateServerBackup(arg1:string):Promise<mcserver.BackupInfo>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeleteServerBackup(arg1:string,arg2:string):Promise<void>;

export function DeleteServerContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportServer(arg1:string,arg2:string):Promise<void>;

export function GetBackupSettings():Promise<mcserver.BackupSettings>;

export function GetServerAutoRestart(arg1:string):Promise<boolean>;

export function GetServerLaunchOptions(arg1:string):Promise<mcserver.LaunchOptions>;

export function GetServerPlayers(arg1:string):Promise<mcserver.ServerPlayers>;

export function GetServerProperties(arg1:string):Promise<Array<mcserver.Property>>;

export function ImportServerMod(arg1:string,arg2:string):Promise<void>;

export function ImportServerNekoser(arg1:string):Promise<string>;

export function ImportServerPlugin(arg1:string,arg2:string):Promise<void>;

export function ImportServerWorld(arg1:string,arg2:string):Promise<void>;

export function InstallServerContentFromModrinth(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ListCoreVersions(arg1:string,arg2:string):Promise<Array<string>>;

export function ListServerBackups(arg1:string):Promise<Array<mcserver.BackupInfo>>;

export function ListServerContent(arg1:string,arg2:string):Promise<Array<mcserver.ServerContentEntry>>;

export function ListServerFiles(arg1:string,arg2:string):Promise<Array<mcserver.FileEntry>>;

export function ListServerMCVersions(arg1:string):Promise<Array<string>>;

export function ListServers():Promise<Array<mcserver.ServerInfo>>;

export function PollServer(arg1:string,arg2:number):Promise<mcserver.Snapshot>;

export function ReadServerTextFile(arg1:string,arg2:string):Promise<string>;

export function RequiredJavaMajor(arg1:string):Promise<number>;

export function RestartServer(arg1:string):Promise<void>;

export function RestoreServerBackup(arg1:string,arg2:string):Promise<void>;

export function RunServerPlayerCommand(arg1:string,arg2:string):Promise<void>;

export function SaveBackupSettings(arg1:mcserver.BackupSettings):Promise<void>;

export function SaveServerBanned(arg1:string,arg2:Array<mcserver.BannedPlayerEntry>):Promise<void>;

export function SaveServerLaunchOptions(arg1:string,arg2:mcserver.LaunchOptions):Promise<void>;

export function SaveServerOps(arg1:string,arg2:Array<mcserver.OpEntry>):Promise<void>;

export function SaveServerWhitelist(arg1:string,arg2:Array<mcserver.WhitelistEntry>):Promise<void>;

export function SearchServerContent(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<models.ModrinthProject>>;

export function SendServerCommand(arg1:string,arg2:string):Promise<void>;

export function ServerContentKindForCore(arg1:string):Promise<string>;

export function SetServerAutoRestart(arg1:string,arg2:boolean):Promise<void>;

export function SetServerContentEnabled(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetServerProperties(arg1:string,arg2:Array<mcserver.Property>):Promise<void>;

export function SetServerWhitelistEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopServer(arg1:string,arg2:boolean):Promise<void>;

export function WriteServerTextFile(arg1:string,arg2:string,arg3:string):Promise<void>;
