// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateServer(arg1) {
  return window['go']['bindings']['ServerHostAPI']['CreateServer'](arg1);
}

export function CreateServerBackup(arg1) {
  return window['go']['bindings']['ServerHostAPI']['CreateServerBackup'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['bindings']['ServerHostAPI']['DeleteServer'](arg1);
}

export function DeleteServerBackup(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['DeleteServerBackup'](arg1, arg2);
}

export function DeleteServerContent(arg1, arg2, arg3) {
  return window['go']['bindings']['ServerHostAPI']['DeleteServerContent'](arg1, arg2, arg3);
}

export function ExportServer(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['ExportServer'](arg1, arg2);
}

export function GetBackupSettings() {
  return window['go']['bindings']['ServerHostAPI']['GetBackupSettings']();
}

export function GetServerAutoRestart(arg1) {
  return window['go']['bindings']['ServerHostAPI']['GetServerAutoRestart'](arg1);
}

export function GetServerLaunchOptions(arg1) {
  return window['go']['bindings']['ServerHostAPI']['GetServerLaunchOptions'](arg1);
}

export function GetServerPlayers(arg1) {
  return window['go']['bindings']['ServerHostAPI']['GetServerPlayers'](arg1);
}

export function GetServerProperties(arg1) {
  return window['go']['bindings']['ServerHostAPI']['GetServerProperties'](arg1);
}

export function ImportServerMod(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['ImportServerMod'](arg1, arg2);
}

export function ImportServerNekoser(arg1) {
  return window['go']['bindings']['ServerHostAPI']['ImportServerNekoser'](arg1);
}

export function ImportServerPlugin(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['ImportServerPlugin'](arg1, arg2);
}

export function ImportServerWorld(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['ImportServerWorld'](arg1, arg2);
}

export function InstallServerContentFromModrinth(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bindings']['ServerHostAPI']['InstallServerContentFromModrinth'](arg1, arg2, arg3, arg4, arg5);
}

export function ListCoreVersions(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['ListCoreVersions'](arg1, arg2);
}

export function ListServerBackups(arg1) {
  return window['go']['bindings']['ServerHostAPI']['ListServerBackups'](arg1);
}

export function ListServerContent(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['ListServerContent'](arg1, arg2);
}

export function ListServerFiles(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['ListServerFiles'](arg1, arg2);
}

export function ListServerMCVersions(arg1) {
  return window['go']['bindings']['ServerHostAPI']['ListServerMCVersions'](arg1);
}

export function ListServers() {
  return window['go']['bindings']['ServerHostAPI']['ListServers']();
}

export function PollServer(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['PollServer'](arg1, arg2);
}

export function ReadServerTextFile(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['ReadServerTextFile'](arg1, arg2);
}

export function RequiredJavaMajor(arg1) {
  return window['go']['bindings']['ServerHostAPI']['RequiredJavaMajor'](arg1);
}

export function RestartServer(arg1) {
  return window['go']['bindings']['ServerHostAPI']['RestartServer'](arg1);
}

export function RestoreServerBackup(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['RestoreServerBackup'](arg1, arg2);
}

export function RunServerPlayerCommand(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['RunServerPlayerCommand'](arg1, arg2);
}

export function SaveBackupSettings(arg1) {
  return window['go']['bindings']['ServerHostAPI']['SaveBackupSettings'](arg1);
}

export function SaveServerBanned(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['SaveServerBanned'](arg1, arg2);
}

export function SaveServerLaunchOptions(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['SaveServerLaunchOptions'](arg1, arg2);
}

export function SaveServerOps(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['SaveServerOps'](arg1, arg2);
}

export function SaveServerWhitelist(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['SaveServerWhitelist'](arg1, arg2);
}

export function SearchServerContent(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['ServerHostAPI']['SearchServerContent'](arg1, arg2, arg3, arg4);
}

export function SendServerCommand(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['SendServerCommand'](arg1, arg2);
}

export function ServerContentKindForCore(arg1) {
  return window['go']['bindings']['ServerHostAPI']['ServerContentKindForCore'](arg1);
}

export function SetServerAutoRestart(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['SetServerAutoRestart'](arg1, arg2);
}

export function SetServerContentEnabled(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['ServerHostAPI']['SetServerContentEnabled'](arg1, arg2, arg3, arg4);
}

export function SetServerProperties(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['SetServerProperties'](arg1, arg2);
}

export function SetServerWhitelistEnabled(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['SetServerWhitelistEnabled'](arg1, arg2);
}

export function StartServer(arg1) {
  return window['go']['bindings']['ServerHostAPI']['StartServer'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['ServerHostAPI']['Startup'](arg1);
}

export function StopServer(arg1, arg2) {
  return window['go']['bindings']['ServerHostAPI']['StopServer'](arg1, arg2);
}

export function WriteServerTextFile(arg1, arg2, arg3) {
  return window['go']['bindings']['ServerHostAPI']['WriteServerTextFile'](arg1, arg2, arg3);
}
