// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {instance} from '../models';
import {context} from '../models';

export function AddLog(arg1:string,arg2:string):Promise<boolean>;

export function ApplyDesktopWallpaper(arg1:string):Promise<void>;

export function ClearLogs():Promise<number>;

export function ClearResourcePackDraft():Promise<void>;

export function ExitLauncher():Promise<void>;

export function ExportCurrentLog(arg1:string):Promise<void>;

export function ExportResourcePack(arg1:string,arg2:Array<bindings.ResourcePackFile>):Promise<string>;

export function FetchRssFeed(arg1:string):Promise<Array<bindings.RssFeedItem>>;

export function GetAcrylicBackdropEnabled():Promise<boolean>;

export function GetBingDailyImagePath():Promise<string>;

export function GetCurrentLog():Promise<string>;

export function GetDesktopWallpaperPath():Promise<string>;

export function GetDeviceId():Promise<string>;

export function GetFormattedVersion():Promise<string>;

export function GetLinuxWallpaperTools():Promise<bindings.LinuxWallpaperTools>;

export function GetWallpaperEngineWallpaper():Promise<bindings.WallpaperEngineWallpaper>;

export function HideLauncher():Promise<void>;

export function ImportResourcePack(arg1:string):Promise<bindings.ResourcePackProject>;

export function ListDirectory(arg1:string):Promise<Array<bindings.SystemFileEntry>>;

export function ListScreenshots(arg1:number):Promise<Array<instance.ScreenshotInfo>>;

export function LoadResourcePackDraft():Promise<bindings.ResourcePackDraft>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function ReadSecret(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveFileAs(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveResourcePackDraft(arg1:bindings.ResourcePackDraft):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetAcrylicBackdropEnabled(arg1:boolean):Promise<boolean>;

export function SetClipboard(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StoreSecret(arg1:string,arg2:string):Promise<boolean>;

export function WriteLog(arg1:string,arg2:string):Promise<boolean>;

export function WritePngFile(arg1:string,arg2:string):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
