// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1, arg2) {
  return window['go']['bindings']['SystemAPI']['AddLog'](arg1, arg2);
}

export function ClearLogs() {
  return window['go']['bindings']['SystemAPI']['ClearLogs']();
}

export function ClearResourcePackDraft() {
  return window['go']['bindings']['SystemAPI']['ClearResourcePackDraft']();
}

export function ExitLauncher() {
  return window['go']['bindings']['SystemAPI']['ExitLauncher']();
}

export function ExportCurrentLog(arg1) {
  return window['go']['bindings']['SystemAPI']['ExportCurrentLog'](arg1);
}

export function ExportResourcePack(arg1, arg2) {
  return window['go']['bindings']['SystemAPI']['ExportResourcePack'](arg1, arg2);
}

export function GetAcrylicBackdropEnabled() {
  return window['go']['bindings']['SystemAPI']['GetAcrylicBackdropEnabled']();
}

export function GetBingDailyImagePath() {
  return window['go']['bindings']['SystemAPI']['GetBingDailyImagePath']();
}

export function GetCurrentLog() {
  return window['go']['bindings']['SystemAPI']['GetCurrentLog']();
}

export function GetDesktopWallpaperPath() {
  return window['go']['bindings']['SystemAPI']['GetDesktopWallpaperPath']();
}

export function GetDeviceId() {
  return window['go']['bindings']['SystemAPI']['GetDeviceId']();
}

export function GetFormattedVersion() {
  return window['go']['bindings']['SystemAPI']['GetFormattedVersion']();
}

export function GetWallpaperEngineWallpaper() {
  return window['go']['bindings']['SystemAPI']['GetWallpaperEngineWallpaper']();
}

export function HideLauncher() {
  return window['go']['bindings']['SystemAPI']['HideLauncher']();
}

export function ImportResourcePack(arg1) {
  return window['go']['bindings']['SystemAPI']['ImportResourcePack'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['bindings']['SystemAPI']['ListDirectory'](arg1);
}

export function ListScreenshots(arg1) {
  return window['go']['bindings']['SystemAPI']['ListScreenshots'](arg1);
}

export function LoadResourcePackDraft() {
  return window['go']['bindings']['SystemAPI']['LoadResourcePackDraft']();
}

export function OpenInExplorer(arg1) {
  return window['go']['bindings']['SystemAPI']['OpenInExplorer'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['bindings']['SystemAPI']['OpenPath'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['bindings']['SystemAPI']['ReadTextFile'](arg1);
}

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['SystemAPI']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function SaveFileAs(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['SystemAPI']['SaveFileAs'](arg1, arg2, arg3, arg4);
}

export function SaveResourcePackDraft(arg1) {
  return window['go']['bindings']['SystemAPI']['SaveResourcePackDraft'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['bindings']['SystemAPI']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['bindings']['SystemAPI']['SelectFile'](arg1, arg2, arg3);
}

export function SetAcrylicBackdropEnabled(arg1) {
  return window['go']['bindings']['SystemAPI']['SetAcrylicBackdropEnabled'](arg1);
}

export function SetClipboard(arg1) {
  return window['go']['bindings']['SystemAPI']['SetClipboard'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['SystemAPI']['Startup'](arg1);
}

export function WriteLog(arg1, arg2) {
  return window['go']['bindings']['SystemAPI']['WriteLog'](arg1, arg2);
}

export function WritePngFile(arg1, arg2) {
  return window['go']['bindings']['SystemAPI']['WritePngFile'](arg1, arg2);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['bindings']['SystemAPI']['WriteTextFile'](arg1, arg2);
}
