// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLauncherUpdate(arg1) {
  return window['go']['bindings']['UpdateAPI']['ApplyLauncherUpdate'](arg1);
}

export function CheckLauncherUpdate(arg1) {
  return window['go']['bindings']['UpdateAPI']['CheckLauncherUpdate'](arg1);
}

export function DownloadLauncherUpdate(arg1) {
  return window['go']['bindings']['UpdateAPI']['DownloadLauncherUpdate'](arg1);
}

export function GetLauncherVersion() {
  return window['go']['bindings']['UpdateAPI']['GetLauncherVersion']();
}

export function Startup(arg1) {
  return window['go']['bindings']['UpdateAPI']['Startup'](arg1);
}
