// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {context} from '../models';

export function ApplyLauncherUpdate(arg1:string):Promise<boolean>;

export function CheckLauncherUpdate(arg1:boolean):Promise<update.CheckResult>;

export function DownloadLauncherUpdate(arg1:update.Asset):Promise<string>;

export function GetLauncherVersion():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
