// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function ApplyLauncherUpdate(arg1:string):Promise<boolean>;

export function CheckLauncherUpdate(arg1:string):Promise<update.CheckResult>;

export function DownloadLauncherUpdate(arg1:update.Asset):Promise<string>;

export function GetAutoUpdateEnabled():Promise<boolean>;

export function GetUpdateChannel():Promise<string>;

export function GetUpdateChannels():Promise<Array<bindings.UpdateChannelOption>>;

export function GetUpdatesEnabled():Promise<boolean>;

export function SaveAutoUpdateEnabled(arg1:boolean):Promise<void>;

export function SaveUpdateChannel(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
